# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import froala_editor.models


class Migration(migrations.Migration):

    dependencies = [
        ('froala_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='froalaaudio',
            name='audio',
            field=models.FileField(upload_to=froala_editor.models.audio_upload_to, verbose_name='音频'),
        ),
        migrations.AlterField(
            model_name='froalaimage',
            name='image',
            field=models.ImageField(upload_to=froala_editor.models.image_upload_to, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='froalasheet',
            name='sheet',
            field=models.FileField(upload_to=froala_editor.models.sheet_upload_to, verbose_name='乐谱'),
        ),
        migrations.AlterField(
            model_name='froalavideo',
            name='video',
            field=models.FileField(upload_to=froala_editor.models.video_upload_to, verbose_name='音频'),
        ),
    ]
